# Generated by Django 3.2.6 on 2021-09-06 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spatialapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('national_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('birthdate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.BigIntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('national_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.driver')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True)),
                ('road_width', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('province_name', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('road_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spatialapp.road')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TollStation',
            fields=[
                ('toll_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('heavy_vehicle_charge', models.IntegerField(blank=True, null=True)),
                ('light_vehicle_charge', models.IntegerField(blank=True, null=True)),
                ('heavy_vehicle_charge_per_kg', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('road_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spatialapp.road')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('road_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatialapp.road')),
                ('toll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.tollstation')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.vehicle')),
            ],
        ),
    ]
