# Generated by Django 3.2.6 on 2021-09-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_payment_road_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='vehicle_id',
            new_name='plate_number',
        ),
        migrations.RenameField(
            model_name='trafficlog',
            old_name='vehicle_id',
            new_name='plate_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.BigIntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
