# Generated by Django 3.2.6 on 2021-08-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_driver_payment_road_tollstation_trafficlog_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='minimum_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='road',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='province_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='road_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.road'),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='road_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
