# Generated by Django 3.2.6 on 2021-08-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20210820_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='road_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.road'),
        ),
    ]
