# Generated by Django 3.2.6 on 2021-09-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20210913_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlog',
            name='road_id',
        ),
    ]
