# Generated by Django 3.2.6 on 2021-08-21 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_trafficlog_road_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='national_code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='road_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.road'),
        ),
    ]
