# Generated by Django 3.2.6 on 2021-08-21 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20210821_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner_id',
            new_name='national_code',
        ),
    ]
