# Generated by Django 3.2.6 on 2021-08-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20210822_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollstation',
            name='heavy_vehicle_charge_per_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tollstation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tollstation',
            name='light_vehicle_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
