# Generated by Django 3.2.6 on 2021-08-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_auto_20210823_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollstation',
            name='heavy_vehicle_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
