# Generated by Django 3.2.6 on 2021-08-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_tollstation_heavy_vehicle_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollstation',
            name='road_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.road'),
        ),
    ]
