# Generated by Django 3.2.6 on 2021-09-06 20:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('road_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('origin', models.CharField(blank=True, max_length=40, null=True)),
                ('destination', models.CharField(blank=True, max_length=40, null=True)),
                ('minimum_height', models.FloatField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
